using System;
using Content.Shared.Sanity;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Sanity.UI
{
    [GenerateTypedNameReferences]
    public partial class SanityWindow : SS14Window
    {
        public SanityWindow()
        {
            RobustXamlLoader.Load(this);
        }

        public void UpdateData(int sanity)
        {
            SanityLineEdit.Text = sanity.ToString();
        }
    }




}
